plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.assistant.core'
    compileSdk 34

    defaultConfig {
        applicationId "com.assistant.core"
        minSdk 26
        targetSdk 34
        versionCode 21
        versionName "3.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles(
                getDefaultProguardFile('proguard-android-optimize.txt'),
                "proguard-rules.pro"
            )
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.activity:activity-ktx:1.9.2'

    implementation 'dev.rikka.shizuku:api:13.1.5'
    implementation 'dev.rikka.shizuku:provider:13.1.5'
    implementation 'dev.rikka.shizuku:aidl:13.1.5'
    implementation 'io.github.iamr0s:Dhizuku-API:2.5.3'
    implementation 'ai.picovoice:porcupine-android:3.0.1'
}
